# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezapa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosier',
            name='tiempo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='sueldo',
            field=models.CharField(max_length=200),
        ),
    ]
